#!/bin/sh

usage() {
	echo usage: $0 log >& 2
}

fatal() {
	echo $@ >& 2
	exit 1
}

plot() {
gnuplot <<EOF
set title "difference of written and read samples using $2"
set yrange  [ -0.01 : +0.01 ]
#set y2range [ -1.00 : +1.00 ]
set terminal png size 1920,480
set output '$2.png'
set nogrid
set nokey

plot '$1' using 1:2 with dots notitle

#plot \
	#'$1' using 1:2 with points pt 7 ps 1 title 'abs', \
	#'$1' using 1:3 with points pt 7 ps 1 title 'rel'
#plot \
	#'$1' using 1:2 with dots title 'abs', \
	#'$1' using 1:3 with dots title 'rel'
EOF
}

which gnuplot > /dev/null || fatal gnuplot not found
test $# -lt 1 && usage && exit 1
LOG="$1"

test -r "$LOG" || fatal "$LOG" is not readable
test -s "$LOG" || fatal "$LOG" is empty
trap "rm $LOG-$$.*" EXIT

split -p pcm $LOG $LOG-$$.
for log in $LOG-$$.* ; do
	format=`head -1 $log | cut -d. -f1`
	awk 'NR > 1 {
		printf "%d %10.8f", $1, $2-$3
		if ($2) printf " %10.8f", ($2-$3)/$2
		printf "\n"
	} ' < $log > $format.diff
	plot $format.diff $format
	#rm -f $format.diff
done
